{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "cidr-allocator.labels" . | nindent 4 }}
  name: {{ include "cidr-allocator.fullname" .}}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cidr-allocator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "cidr-allocator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "cidr-allocator.labels" . | nindent 4 }}
  name: {{ include "cidr-allocator.fullname" .}}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cidr-allocator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "cidr-allocator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
