{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}-pgbouncer
  labels:
    app.kubernetes.io/name: {{ include "ckan.fullname" . }}
    helm.sh/chart: {{ include "ckan.chart" . }}
    app.kubernetes.io/instance: {{ include "ckan.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  pgbouncer.ini: {{ tpl (.Files.Get "conf/pgbouncer/pgbouncer.ini") . | b64enc }}
  userlist.txt: {{ tpl (.Files.Get "conf/pgbouncer/userlist.txt") . | b64enc }}
{{- end }}
