{{- if .Values.ckan.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ckan.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "ckan.fullname" . }}
    helm.sh/chart: {{ include "ckan.chart" . }}
    app.kubernetes.io/instance: {{ include "ckan.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ckan.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
