apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vetting-app.fullname" . }}-static-error-deployment
  labels:
    app.kubernetes.io/name: {{ include "vetting-app.name" . }}-static-error
    helm.sh/chart: {{ include "vetting-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vetting-app.name" . }}-static-error
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vetting-app.name" . }}-static-error
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - disclosure-vetting
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: {{ .Chart.Name }}-static-error
          image: "{{ .Values.appImageStaticError.repository }}:{{ .Values.appImageStaticError.tag }}"
          imagePullPolicy: {{ .Values.appImageStaticError.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
